import { LootItem } from '@/shared/types/loot'

export const testItems: LootItem[] = [
  {
    name: 'Test',
    quantity: 100,
    stackable: true,
    imageSource: require('../../../assets/images/ak.png'),
    weight: 1.5,
    width: 11,
    height: 4,
  },
  {
    name: 'Test',
    quantity: 3,
    stackable: true,
    imageSource: require('../../../assets/images/akm.png'),
    weight: 1.5,
    width: 11,
    height: 4,
  },
  {
    name: 'Test',
    quantity: 3,
    stackable: true,
    imageSource: require('../../../assets/images/akm.png'),
    weight: 1.5,
    width: 11,
    height: 4,
  },
  {
    name: 'Test',
    quantity: 2,
    stackable: false,
    imageSource: require('../../../assets/images/compass-artifact.png'),
    weight: 2,
    width: 4,
    height: 4,
  },
  {
    name: 'Test',
    quantity: 1,
    stackable: false,
    imageSource: require('../../../assets/images/exoskeleton.png'),
    weight: 2,
    width: 5.49,
    height: 8,
  },
  {
    name: 'Test',
    quantity: 1,
    stackable: false,
    imageSource: require('../../../assets/images/exoskeleton.png'),
    weight: 2,
    width: 5.49,
    height: 8,
  },
  {
    name: 'Test',
    quantity: 1,
    stackable: false,
    imageSource: require('../../../assets/images/exoskeleton.png'),
    weight: 2,
    width: 5.49,
    height: 8,
  },
  {
    name: 'Test',
    quantity: 2,
    stackable: false,
    imageSource: require('../../../assets/images/compass-artifact.png'),
    weight: 2,
    width: 4,
    height: 4,
  },
  {
    name: 'Test',
    quantity: 1,
    stackable: false,
    imageSource: require('../../../assets/images/exoskeleton.png'),
    weight: 2,
    width: 5.49,
    height: 8,
  },
  {
    name: 'Test',
    quantity: 2,
    stackable: false,
    imageSource: require('../../../assets/images/compass-artifact.png'),
    weight: 2,
    width: 5,
    height: 4,
  },
  {
    name: 'Test',
    quantity: 2,
    stackable: false,
    imageSource: require('../../../assets/images/compass-artifact.png'),
    weight: 2,
    width: 5,
    height: 4,
  },
  {
    name: 'Test',
    quantity: 2,
    stackable: false,
    imageSource: require('../../../assets/images/compass-artifact.png'),
    weight: 2,
    width: 4,
    height: 4,
  },
  {
    name: 'Test',
    quantity: 100,
    stackable: true,
    imageSource: require('../../../assets/images/ak.png'),
    weight: 1.5,
    width: 11,
    height: 4,
  },
]

export const MAX_INVENTORY_WEIGHT = 100
export const CELL_SIZE = 16.6
